### ISSUE TITLE
Compile Error in Arduino 1.8.12

### ISSUE THREAD

**Issue by j-lang** [iseries1/BWiFi#1]
Did you compile this source on current arduino versions. 
In Arduino 1.8.12 I get errors starting with:

<command-line>:0:9: error: expected identifier before numeric constant

sketch\ESP8266.h:7:7: note: in expansion of macro 'ESP8266'

 class ESP8266 {

       ^

By the way: I built a B-Robot with parts lying around (Beetle 32U4 Board and CNC shield) and found  your code for adding an ESP8266-01 for wifi communication.

**Comment by iseries1** [comment]
I just compiled it with 1.8.5 and I get that error if I select board type ESP8266.  You need to compile it with Arduino Leonardo which is what board is used for this project.  The Leonardo board reprograms the ESP8266.

**Comment by j-lang** [comment]
Ok, my failure, with this "Leonardo" firmware you can communicate with the onboard ESP8266 an can configure it. The ESP8266 firmware is still untouched. Do you know where to find the ESP8266 OSC firmware used for B-Robot?

**Comment by iseries1** [comment]
This is the default firmware that comes with a new ESP8266 module.  The AT command firmware that can be found here: https://github.com/espressif/ESP8266_NONOS_SDK.

**Comment by j-lang** [comment]
Thank you!

**Comment by iseries1** [comment]
Wrong board selected.
